### PR TITLE
Update the license definition.

### PR DESCRIPTION
**Pull request by ilg-ul**
Update the module.json reference page to reflect that the new syntax is a single string, not an array of objets.

### CODE REVIEW

**Comment by autopulated** [comment]
Thanks for contributing! I will merge along with a note of the old property so that it's still documented if someone comes across it.

Please could you click-through our CLA (http://developer.mbed.org/contributor_agreement/) by signing in with a http://developer.mbed.org account, and let me know your mbed account name so that I can merge :smile:

**Comment by ilg-ul** [comment]
> mbed account name

`ilg`

**Comment by autopulated** [comment]
:white_check_mark: confirmed mbed 2.0 CLA click-through as ilg

will merge & publish to docs page shortly

**Comment by ilg-ul** [comment]
the http://yottadocs.mbed.com/reference/target.html also mentions `licenses`, could you update it too?

**Comment by autopulated** [comment]
yup, on it :)

**Comment by ilg-ul** [comment]
two more questions:

* when you create new modules, does yotta now generate the new `license` or the old `licenses`?
* modules that now use `licenses` will remain like this until manually edited, or will `yotta` update them the next time it writes the json files?

**Comment by autopulated** [comment]
yotta won't update/convert. It will use the `license` when you run `yotta init` though (that changed in #492 / yotta 0.8.5)

**Comment by ilg-ul** [comment]
> yotta won't update/convert

is there any command to spot deprecated configs? a `yotta validate` or similar?

**Comment by autopulated** [comment]
yotta will issue warnings whenever it parses a file with invalid schema, so any command like `yotta ls` will check it – I'm not sure if there's a way of marking something as suppored-but-deprecated in JSON schema though? (@geraintluff?) But if there is we can do that.

**Comment by ilg-ul** [comment]
my suggestion was not explicit enough: yotta checks the schema whenever it parses a file, and I guess this is enough to prevent the use of invalid files. in addition to this yes/no result, `yotta validate` would add some code to check behind the schema, and would also cover cases like deprecated syntax (and probably more, that cannot be described by a schema)

**Comment by autopulated** [comment]
Ok, got it. Could you add a comment on #451 so it doesn't get lost?

**Comment by ilg-ul** [comment]
> add a comment ...

done

**Pull request merged**
