### PR TITLE
Adds a requirements.txt file for development

### PR DESCRIPTION
**Pull request by kushaldas**
One can use this by $ pip install -r requirements.txt
command.

### CODE REVIEW

**Comment by autopulated** [comment]
To install yotta for development, I do:

`pip install -e .`

in the source I'm editing/testing.

Perhaps I'm missing something, as requirements.txt seems to be a common pattern, but what does moving the dependency specifications from setup.py to requirements.txt make possible?

**Comment by kushaldas** [comment]
The differences are mentioned at https://python-packaging-user-guide.readthedocs.org/en/latest/requirements/#requirements-files

**Comment by kushaldas** [comment]
Feel free to close the PR if you think, I added that as a general thing most Python projects have.

**Comment by autopulated** [comment]
OK got it. I'd feel icky duplicating the requirements list, so I'll close this for now.

Possibly it could be useful to use requirements.txt to store a known-good version of dependencies recursively in the future, for packaging into our installers for example.

**Pull request closed without merging**
