### PR TITLE
fix #303 - still try to run tests if the build status is nonzero

### LINKED ISSUE #303: Inconsistent 'yotta test' behaviour
When one or more mismatched dependency errors are reported on a repository, `yotta build` can still be executed, and it might succeed. However, 'yotta test' will stop after building, without trying to actually run any tests.

### PR DESCRIPTION
**Pull request by autopulated**

### CODE REVIEW

**Comment by bogdanm** [comment]
I'm not sure this is right. A `build failure` should probably prevent tests from running (because what would you run?). An invalid dependency error which does *not* actually lead to a build failure is a different thing.

**Comment by autopulated** [comment]
so many different types of "error" :sob:

**Comment by autopulated** [comment]
how's that @bogdanm?

**Comment by bogdanm** [comment]
Looks much better! +1.

**Pull request merged**
