### PR TITLE
improve github authentication handling decorator:

### LINKED ISSUE #539: Require a way to log in to github
When I use a github dependency in yotta and am behind a proxy, github can reach anonymous download limits and refuse to serve requests:

```
github.GithubException.GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u"API rate limit exceeded for 81.134.128.130.
```

Can yotta be made to allow github logins?

### PR DESCRIPTION
**Pull request by autopulated**
( treat rate-limit-exceeded errors as requiring auth, and reduce code duplication)

Fixes #539 

cc @thegecko

### CODE REVIEW

**Comment by markus-becker-tridonic-com** [comment]
Will you release a new version including this soon to pypi? Would help us a lot.

**Comment by autopulated** [comment]
:+1: will do soon

**Comment by autopulated** [comment]
(now live in yotta 0.9.2)

**Comment by markus-becker-tridonic-com** [comment]
thanks

**Pull request merged**
