### PR TITLE
yotta windows install script

### PR DESCRIPTION
**Pull request by BlackstoneEngineering**
I created a branch for a windows install script i'm working on. 
Currently the script pulls down dependencies for windows only, it can differentiate between 32bit and 64bit. 
The script then runs the isntallers in order and prompts the user to click through them. 

In the future I would like to make these installers silent, but that requires some brute force hacking on the exe's and registry editing. If there is demand can work on this later.

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
Updated the script, should be added in or released in one form or another now.

**Comment by autopulated** [comment]
:+1: Thanks, looks good!

**Comment by sg-** [comment]
We'll need to somehow check for installed programs in the future. In some cases tools will already be installed on developers computers

**Comment by autopulated** [comment]
I hope that in the context that get_yotta.py is mentioned in the [installation instructions](http://docs.yottabuild.org/#installing-on-windows), it's clear that it is only needed to set up the environment for the first time, so while that'd be nice I don't think it's critical.

It's hard to judge the level of hand-holding that these instructions need until we've had exposure to a large number of people trying them.

**Comment by BlackstoneEngineering** [comment]
@sg, I added that in this release, it now checks to see if the program is installed on the computer (findable in the path) and asks if the user wants to re-install it.

@autopulated - I believe this script is necessary for windows users. Also this script doesnt have to live in the yotta repo, we can put it anywhere we please, it can live on its own and has no dependencies on yotta, just submitting it here because i thought it would be the best place to get attention and get er done.

**Comment by sg-** [comment]
I already have GCC installed on my developer machine. I'm now watching it download gcc because it didn't ask me if its already installed. Bad experience.

**Comment by BlackstoneEngineering** [comment]
@sg- true, add it either her or on jira for Alpha3 and i'll get er done, theres a bunch i want to do for this script, like silent installers, that hasnt been done due to time constraints.

**Comment by sg-** [comment]
Issue created for tracking. https://github.com/ARMmbed/yotta/issues/209

**Pull request merged**
