### PR TITLE
Add --json switch to 'yt target' option

### PR DESCRIPTION
**Pull request by PrzemekWirkus**
# Description
We want to easily parse some commands in automation. It is easier if commands like ```yt ls --json``` return JSOn formatted data. 
We need at least:
* ```yt target```,
* ```yt search```,
* ```yt ls``` (already available with auxilary ```--json```) and
* ```yt target``` - implemented in this PR.

# Changes
* Add option ```--json``` / ```-j``` to ````yotta target```.
* Option ```--json``` for ```yt target``` implicitly forces ```--plain``` (no colorama formatting).

# Examples
```
$ yt target
frdm-k64f-gcc 2.0.0
kinetis-k64-gcc 2.0.2
mbed-gcc 1.1.0

$ yt target -j
{
  "frdm-k64f-gcc": "2.0.0",
  "kinetis-k64-gcc": "2.0.2",
  "mbed-gcc": "1.1.0"
}
```

```
$ yt target xxx
info: get versions for xxx
error: could not install target xxx at * for xxx
error: xxx does not exist in the targets registry. Check that the name is correct, and that it has been published.
error: NOTE: use "yotta link-target" to test a locally modified target prior to publishing.

$ yt target -j
{
  "xxx,*": "missing"
}
```

### CODE REVIEW

**Comment by PrzemekWirkus** [comment]
@autopulated please review.

**Comment by autopulated** [comment]
Thanks for contributing! – I think there are two things to improve:

 * The format should correspond to the `yt ls --json` format (except with targets instead of modules):

```
  {
    "modules": [
      {
        "name": "example-mbedos-blinky",
        "version": "4.5.6+foo-something.2.3.4",
        "path": "/wherever/...",
        ... 
      },
      ...
    ]
  }
```

 * It feels a bit weird that we're constructing a dictionary with colour codes in the keys and values (although they will never actually end up there): seems like it'd be better to add the formatting when processing the datastructure for display.

**Comment by PrzemekWirkus** [comment]
OK, I will check your comments in free time. Thanks :)

**Comment by PrzemekWirkus** [comment]
I will close this PR, this feature is no longer required.

**Pull request closed without merging**
