### PR TITLE
Working on resolving #403

### LINKED ISSUE #403: build information as compile time defines
there should be several defines which YOTTA generates build time:

* YOTTA_BUILD_DATE
* YOTTA_BUILD_TIME
* YOTTA_BUILD_SCM_HASH   (GIT/HG HASH)
* YOTTA_BUILD_UUID (generated by yotta)

Those are very important for example when verify that software under test is what we expect..

### PR DESCRIPTION
**Pull request by autopulated**
Resolves #403

### CODE REVIEW

**Comment by autopulated** [comment]
Initial experiments seem to suggest that the dependency on the build-info header being included via ` `#include YOTTA_BUILD_INFO_HEADER` **is** being correctly tracked, which is pleasantly surprising.

**Comment by autopulated** [comment]
(still to come before merging: documentation updates)

**Comment by jupe** [comment]
looks great :)

**Comment by jupe** [comment]
I'll start using this directly when this is merged and published!

**Pull request merged**
