### PR TITLE
add reference/cheatsheet

### PR DESCRIPTION
**Pull request by autopulated**
cc @BlackstoneEngineering

### CODE REVIEW

**Comment by autopulated** [comment]
screen shot 2015-10-16 at 10 23 46

**Comment by 0xc0170** [comment]
neat ! +1

**Comment by 0xc0170** [comment]
Commands I use the most, not in the sheet: 
- yotta target
- yotta list
- yt link

There are not there, to keep it simple ?

**Comment by autopulated** [comment]
yotta target is there! yotta list is definitely an omission, you're right, yotta link I'm not sure about

**Comment by BlackstoneEngineering** [comment]
Note this is an alpha, it is encouraged that we expand it, This cheetsheet is a direct result of a recent meetup i hosted and questions i got about yotta / references needed. I intend to expand it as I go along, any suggestions are always welcome!!

**Pull request merged**
