### PR TITLE
Add wrapper method to fix issue #856

### PR DESCRIPTION
**Pull request by psch2**

### CODE REVIEW

**Comment by jamesadevine** [comment]
Hiya, can we expedite this fix? It is affecting users of the micro:bit ecosystem.

I applied it locally and it ran fine, it seems your CI build is broken.

**Comment by jamesadevine** [comment]
Thanks @thegecko :smile:

**Comment by thegecko** [comment]
Yup, CI has borked again. Package updates between builds do that.

**Comment by jamesadevine** [comment]
@thegecko Would it be possible to do a pip deploy?

**Comment by jamesadevine** [comment]
@thegecko What's the best way to assist? I don't know how to repro the error locally, I tried to run the test but am not encountering the same error as the CI...

**Pull request merged**
