### PR TITLE
add a run command to run user scripts defined in module.scripts

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Addresses #611 and #109

### CODE REVIEW

**Comment by autopulated** [comment]
Ah, I just started work on this, diff here: https://github.com/ARMmbed/yotta/compare/master...autopulated:scripting?expand=1

Would my start/run command cover what you need?

**Comment by jacobrosenthal** [comment]
Sure. I think the only thing you dont do that I do is print the output to
console, Id recommend that

**Comment by autopulated** [comment]
As the output isn't captured it should go straight to the controlling terminal :)

**Comment by autopulated** [comment]
Closing this as alternative support has been merged now :)

**Comment by jacobrosenthal** [comment]
What commit did this go in under? How do you use it?

**Pull request closed without merging**
