### PR TITLE
yotta: Update version for 0.14.2 bugfix release

### PR DESCRIPTION
**Pull request by kylemanna**
* With out this yotta reports the wrong version.

### CODE REVIEW

**Comment by autopulated** [comment]
Thanks – this was a missed push on my part. It should be fixed now.

**Comment by kylemanna** [comment]
Thanks!

**Comment by kylemanna** [comment]
@autopulated Can you bump the [release tag](https://github.com/ARMmbed/yotta/releases) to include this?  I maintain some packages that pull from the release source tarballs.

**Comment by autopulated** [comment]
Should be updated now.

If it's helpful, I always upload the same source tarball which is published to pip to the github releases page (the yotta-0.14.2.tar.gz link), this has only the files which are actually published (the CI configuration is stripped out, for example).

**Pull request closed without merging**
