### PR TITLE
Target Tab Completion

### PR DESCRIPTION
**Pull request by BlackstoneEngineering**
## Problem
manually typing out the target for yotta is a pain and error prone (its entirely possible to set a target that is invalid and you'll never know till you go to compile for it)

## Solution
Added tab completion for the -t --target option. 

## Demo
run `yotta target -u` to update the local cache of targets
run `yotta -t fr<tab>` to have it tab complete (currently to `frdm-k64f-gcc` or `frdm-k64f-armcc`)

## Nitty Gritty
Added cache.py file that creates an basic cachine system in `~/yotta/cache/`, it has two simple access functions, get and set. It leaves all the accessors and pretty stuff up to whatever is using it. All data is stored in un-ordered JSON. If the cache folder doesnt exist it will create it, if the cache file doesnt exist it will create it, if the cache file does exist it will overwrite it (ie a call to cache.set('target',x) followed by a call to cache.set('target',y) would result in the x data being overwritted by the y data. 

The tab completion function accesses the local cache of target names and completes from them. 

## Future improvement
Add zsh tab completions. Add periodic updating of targets cache (maybe the first time the command is run that day? first time every hour? ....?)

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
Fix for https://github.com/ARMmbed/yotta/issues/219

**Comment by BlackstoneEngineering** [comment]
Failed CI, figured out why, closing pull request to re-open shortly with fix implimented.

**Comment by 0xc0170** [comment]
You can just fix it in the open PR, don't need to close/open a new one. 
Although I see here the fix commit..

**Comment by BlackstoneEngineering** [comment]
It was 1am and I couldn't figure it out

**Pull request closed without merging**
