### PR TITLE
Updated version to fix PyPI issue

### PR DESCRIPTION
**Pull request by bogdanm**
This commit updates the yotta version just to make it possible to
upload a new version to PyPI, since the previous one (0.17.1)
doesn't have its bin/ directory and doesn't install at all in
Linux.

### CODE REVIEW

**Comment by bogdanm** [comment]
@0xc0170

**Comment by thegecko** [comment]
ACK

**Comment by bogdanm** [comment]
Lesson learnt: do *not* publish to PyPI from Windows. Weird stuff happens. By which I mean "you won't get a bin/ directory in your distro at all". This is something we might want to fix in the future.

**Comment by 0xc0170** [comment]
> Lesson learnt: do not publish to PyPI from Windows. Weird stuff happens. By which I mean "you won't get a bin/ directory in your archive at all". This is something we might want to fix in the future.

Please create a tracking issue with your findings

**Comment by bogdanm** [comment]
Created #798 to track this.

**Pull request merged**
