### PR TITLE
Add relative git path example

### PR DESCRIPTION
**Pull request by Timmmm**
This took me ages to work out. Lots of things you'd think should work, don't. It should definitely be in the docs.

### CODE REVIEW

**Comment by autopulated** [comment]
Support for this wasn't intentional! I guess there's no reason it shouldn't work, but obviously publishing a module which does this would cause people who try to use it problems unless the relative path is somewhere inside the same module.

**Comment by Timmmm** [comment]
Aha well, it is very useful anyway! I don't see another way to do development with private libraries very easily. There is already a check on the public server to prevent modules with github dependencies. I guess the best thing to do is to prevent local dependencies too.

By the way this depends on pull request #780

**Comment by thegecko** [comment]
I'd rather this wasn't documented until we have testing around. @Timmmm Happy for me to close this PR?

**Comment by Timmmm** [comment]
Err yeah. I thought yotta had been superceded by mbed 5?

**Comment by thegecko** [comment]
Hi @Timmmm, yotta isn't tied to mbed OS, but you are correct, it's no longer used to build it since version 5.

**Pull request closed without merging**
