### PR TITLE
Update cheatsheet.md

### PR DESCRIPTION
**Pull request by ranshe**
Added "common errors" - currently under Targets since this is the only error I'm familiar with, but it might be better to have this as a standalone section and fill it with errors from other aspects of the system as well (also common run-time systems)

### CODE REVIEW

**Comment by autopulated** [comment]
To update the docs please open a pull request against the ./docs folder on the master branch. (We push that subdirectory to the gh-pages branch.)

In this case I'm wondering if we can do something better than just adding a warning to the cheatsheet though, for example we could add the warning in the actual error message here: https://github.com/ARMmbed/mbed-hal-k64f/blob/master/source/CMakeLists.txt#L73 so that everyone who sees the error will be aware of the possible cause?

**Comment by ranshe** [comment]
I agree - it will be MUCH better to edit the error message to indicate what
it actually means :-)

**Comment by autopulated** [comment]
:thumbsup: I'll leave this open until it's fixed at the source.

**Comment by thegecko** [comment]
PR no longer valid

**Pull request closed without merging**
