### PR TITLE
Improve the content of ls --json output

### PR DESCRIPTION
**Pull request by bremoran**
semantics for “missing” appear to still be wrong.

### CODE REVIEW

**Comment by autopulated** [comment]
FWIW, this is the --json format that npm has:

```
{
  "name": "root",
  "version": "1.0.0",
  "dependencies": {
    "circletest": {
      "version": "1.0.0",
      "dependencies": {
        "circletest-2": {
          "version": "1.0.0"
        }
      }
    }
  }
}
```

(root depends on circletest, and both circletest modules depend on each other)

i.e. circular dependencies aren't shown. If there are version errors you get a `"problems": []` item, but the error descriptions aren't particularly helpful.

**Comment by autopulated** [comment]
How about this:

```JSON
{
  "name": "root",
  "version": "1.0.0",
  // no specification on the root module
  "dependencies": {
    "circletest": {
      "specification": "^1.0.0", // specification of root on circletest
      "version": "1.0.0",
      "satisfiedBy": "/path/on/disk/circletest", // or null if missing
      "linkedTo": "/real/path/on/disk/circletest", // or null/not present if not linked?
      "dependencies": {
        "circletest-2": {
          "version": "1.0.0",
          "specification": "^1.0.0",
          "satisfiedBy": "/path/on/disk/circletest-2",
          "linkedTo": "/real/path/on/disk/circletest-2",
          "dependencies": {
            "specification": "^1.0.0", // specification of circletest-2 on circletest
            "version": "1.0.0",
            "satisfiedBy": "/path/on/disk/circletest",
            "linkedTo": "/real/path/on/disk/circletest",
             // circular dependency does not have its own dependencies section repeated when it occurs a second time
          }
        }
      }
    }
  }
}
```

**Comment by bremoran** [comment]
I don't understand why the content needs to be nested.

**Comment by autopulated** [comment]
because what it's trying to represent *is* nested

**Comment by bremoran** [comment]
I disagree. It's not nested.  It's trying to represent a graph, with nodes and edges.  _One_ way to represent that is nesting, but that only works for a tree graph, which dependencies are not.  _Another_ way to represent a graph is to list all the nodes and all the edges.

**Comment by autopulated** [comment]
Closing this as json format will change as part of #508, you've persuaded me it should be flat though ;)

**Comment by thegecko** [comment]
I disagree the default output should be flat, the current structure is representative of the actual dependency structure.

How about a flag to flatten the dependency graph into a list?

**Comment by autopulated** [comment]
Two options would be worse than either, I think ;)

It should be flat because if it's nested, the position at which things appear in the tree becomes a potential source of errors, and likely something that will need to be kept stable, and as @bremoran says: the dependencies are really a graph, not a tree. Choosing a tree to represent a graph is tricky, whereas an edge/node list is straightforward.

**Comment by bremoran** [comment]
You can tell that the dependencies are a graph, not a tree like this: if you take all the module.json's and process them so that config is handled, what you have left is a node/edge list. That's a graph.

**Pull request closed without merging**
